//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KfpWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MondayGuess
    {
        public int id { get; set; }
        public string userId { get; set; }
        public int gameId { get; set; }
        public int guess { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string userCreatedId { get; set; }
        public bool deleted { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User UserCreated { get; set; }
        public virtual User User { get; set; }
    }
}
