//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KfpWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.AwayGames = new HashSet<Game>();
            this.FavoriteGames = new HashSet<Game>();
            this.HomeGames = new HashSet<Game>();
            this.WinningGames = new HashSet<Game>();
            this.Points2Picks = new HashSet<Pick>();
            this.Points3Picks = new HashSet<Pick>();
            this.Points5Picks = new HashSet<Pick>();
        }
    
        public string id { get; set; }
        public string city { get; set; }
        public string name { get; set; }
        public string logoUrl { get; set; }
    
        public virtual ICollection<Game> AwayGames { get; set; }
        public virtual ICollection<Game> FavoriteGames { get; set; }
        public virtual ICollection<Game> HomeGames { get; set; }
        public virtual ICollection<Game> WinningGames { get; set; }
        public virtual ICollection<Pick> Points2Picks { get; set; }
        public virtual ICollection<Pick> Points3Picks { get; set; }
        public virtual ICollection<Pick> Points5Picks { get; set; }
    }
}
