//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KfpWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.MondayGuessesCreated = new HashSet<MondayGuess>();
            this.MondayGuesses = new HashSet<MondayGuess>();
            this.PicksCreated = new HashSet<Pick>();
            this.Picks = new HashSet<Pick>();
        }
    
        public string id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string nickname { get; set; }
        public string pictureUrl { get; set; }
        public string location { get; set; }
        public string status { get; set; }
        public string pastChampion { get; set; }
        public string role { get; set; }
        public string password { get; set; }
        public bool sendReminder { get; set; }
        public bool paid { get; set; }
        public bool active { get; set; }
        public System.DateTime lastActive { get; set; }
    
        public virtual ICollection<MondayGuess> MondayGuessesCreated { get; set; }
        public virtual ICollection<MondayGuess> MondayGuesses { get; set; }
        public virtual ICollection<Pick> PicksCreated { get; set; }
        public virtual ICollection<Pick> Picks { get; set; }
    }
}
